#!/usr/bin/env bash

if [[ -d /boot/firmware ]]; then
    PICONFIG_BOOT_DIR="/boot/firmware"
else
    PICONFIG_BOOT_DIR="/boot"
fi

[ -n "${PICONFIG_CONFIG_TXT_FILE:-}" ] || \
    PICONFIG_CONFIG_TXT_FILE="${PICONFIG_BOOT_DIR}/config.txt"

[ -n "${PICONFIG_CMDLINE_TXT_FILE:-}" ] || \
    PICONFIG_CMDLINE_TXT_FILE="${PICONFIG_BOOT_DIR}/cmdline.txt"

[ -n "${PICONFIG_CONFIG_BAK_FILE:-}" ] || \
    PICONFIG_CONFIG_BAK_FILE="${PICONFIG_BOOT_DIR}/config.txt.backup"

[ -n "${PICONFIG_CMDLINE_BAK_FILE:-}" ] || \
    PICONFIG_CMDLINE_BAK_FILE="${PICONFIG_BOOT_DIR}/cmdline.txt.backup"

[ -n "${PICONFIG_SWAP_CONF_FILE:-}" ] || \
    PICONFIG_SWAP_CONF_FILE="/etc/dphys-swapfile"

[ -n "${PICONFIG_SWAP_SIZE:-}" ] || \
    PICONFIG_SWAP_SIZE="256"

[ -n "${PICONFIG_SWAP_MAX:-}" ] || \
    PICONFIG_SWAP_MAX="1024"
