#!/usr/bin/env bash
#### MainsailOS Build Chain
####
#### Klipper Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021 - 2022
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces

set -Eex

export LC_ALL=C

if [[ "${DEBIAN_FRONTEND:-}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Install Input Shaper requirements ..."

apt-get update

echo_green "Installing Input Shaper dependencies ..."

if [[ -n "${IS_REQ_PREINSTALL_DEPS//[[:space:]]/}" ]]; then
    # Intentionally split the package list into separate arguments.
    # shellcheck disable=SC2086
    check_install_pkgs ${IS_REQ_PREINSTALL_DEPS}
else
    echo_green "No APT dependencies configured; skipping."
fi

if [[ -z "${BASE_USER:-}" ]]; then
    echo_red "BASE_USER is not configured!"
    exit 1
fi

if [[ -z "${IS_REQ_PREINSTALL_VENV_DIR:-}" ]]; then
    echo_red "IS_REQ_PREINSTALL_VENV_DIR is not configured!"
    exit 1
fi

pushd "/home/${BASE_USER}" >/dev/null || exit 1

VENV_PYTHON="${IS_REQ_PREINSTALL_VENV_DIR}/bin/python"

if [[ ! -x "${VENV_PYTHON}" ]]; then
    echo_red "Klipper virtual environment not found: ${IS_REQ_PREINSTALL_VENV_DIR}"
    popd >/dev/null || true
    exit 1
fi

if [[ -n "${IS_REQ_PREINSTALL_PIP:-}" ]] &&
   [[ -n "${IS_REQ_PREINSTALL_PIP//[[:space:]]/}" ]]; then

    echo_green "Installing pip packages: ${IS_REQ_PREINSTALL_PIP}"

    # Convert the space-separated package list into an array.
    read -r -a PIP_PACKAGES <<< "${IS_REQ_PREINSTALL_PIP}"

    runuser -u "${BASE_USER}" -- \
        "${VENV_PYTHON}" -m pip install \
        --disable-pip-version-check \
        -v \
        "${PIP_PACKAGES[@]}"
else
    echo_green "No pip dependencies configured; skipping pip installation."
fi

echo_green "Cleanup ..."

rm -rf "/home/${BASE_USER}/.cache"
chown -R "${BASE_USER}:${BASE_USER}" "/home/${BASE_USER}" 2>/dev/null || true

popd >/dev/null || exit 1

echo_green "Install Input Shaper requirements ... done!"
